# Generated by Django 4.2.7 on 2023-11-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('progress', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=2)),
                ('completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
