# Generated by Django 4.2.7 on 2023-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_e', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Light'), (2, 'Dark')], default=1),
        ),
    ]
